## ML tentative 1

In [13]:
import pandas as pd

In [14]:
data = pd.read_pickle("infos_games.pickle")

In [15]:
data

,GameId,GameDuration,gameMode,win,championName1,championName2,championId1,championId2,champExperience1,champExperience2,champLevel1,champLevel2
0,EUW1_6111736235,1024,URF,2,"[Syndra, KogMaw, Sylas, Pyke, MasterYi]","[Tristana, Shen, Akshan, Sylas, Veigar]","[134, 96, 517, 555, 11]","[18, 98, 166, 517, 45]","[12879, 20166, 18061, 16976, 15447]","[20869, 22586, 19536, 23164, 19358]","[14, 18, 17, 17, 16]","[19, 20, 18, 20, 18]"
1,EUW1_6111632386,1153,URF,2,"[Garen, Nunu, Kassadin, Lux, Akali]","[Ashe, Jhin, Jayce, Ziggs, Gragas]","[86, 20, 38, 99, 84]","[22, 202, 126, 115, 79]","[16701, 18567, 23469, 19051, 20011]","[23563, 22385, 24451, 25024, 22559]","[17, 18, 20, 18, 18]","[20, 20, 21, 21, 20]"
2,EUW1_6110745821,883,URF,1,"[Velkoz, Hecarim, Trundle, Talon, Zed]","[Veigar, Zyra, Ashe, Draven, Blitzcrank]","[161, 120, 48, 91, 238]","[45, 143, 22, 119, 53]","[16877, 14785, 14846, 16342, 14172]","[11132, 13279, 12272, 12910, 13703]","[17, 16, 16, 16, 15]","[13, 15, 14, 14, 15]"
3,EUW1_6110639675,1325,URF,2,"[Ezreal, Nunu, Morgana, Veigar, Kaisa]","[Skarner, Alistar, Samira, Veigar, Rakan]","[81, 20, 25, 45, 145]","[72, 12, 360, 45, 497]","[24293, 20427, 23124, 24203, 24537]","[25508, 28887, 25429, 27971, 23500]","[21, 19, 20, 21, 21]","[21, 23, 21, 23, 20]"
4,EUW1_6110065467,1113,URF,1,"[Yone, Ashe, Ziggs, Jinx, Heimerdinger]","[Volibear, Kled, Zed, Gwen, LeeSin]","[777, 22, 115, 222, 74]","[106, 240, 238, 887, 64]","[16230, 21698, 20541, 22187, 21144]","[20834, 21903, 18562, 18892, 19652]","[16, 19, 19, 20, 19]","[19, 19, 18, 18, 18]"
...,...,...,...,...,...,...,...,...,...,...,...,...
95,EUW1_6030308673,2173,CLASSIC,2,"[Gwen, MasterYi, Yone, Nilah, Pyke]","[Darius, Ekko, TwistedFate, Sivir, Morgana]","[887, 11, 777, 895, 555]","[122, 245, 4, 15, 25]","[20751, 20505, 18370, 22736, 15515]","[17795, 20793, 20403, 20821, 18287]","[18, 18, 18, 18, 16]","[17, 18, 18, 18, 17]"
96,EUW1_6030124988,2344,CLASSIC,2,"[Renekton, Udyr, Viktor, Ezreal, Lux]","[Darius, Kayn, Taliyah, Twitch, Morgana]","[58, 77, 112, 81, 99]","[122, 141, 163, 29, 25]","[17049, 15276, 15836, 15776, 13348]","[21241, 21296, 19913, 16173, 15388]","[17, 16, 16, 16, 15]","[18, 18, 18, 16, 16]"
97,EUW1_6029974109,1865,CLASSIC,2,"[Darius, Udyr, Orianna, Caitlyn, Xerath]","[Warwick, Nocturne, Chogath, MissFortune, Zyra]","[122, 77, 61, 51, 101]","[19, 56, 31, 21, 143]","[11537, 12237, 14498, 12536, 10741]","[18541, 15287, 16196, 16508, 11526]","[14, 14, 15, 14, 13]","[18, 16, 16, 17, 14]"
98,EUW1_6029836748,1212,CLASSIC,1,"[Darius, MasterYi, Sylas, Caitlyn, Braum]","[MonkeyKing, Sejuani, Syndra, Draven, Blitzcrank]","[122, 11, 517, 51, 201]","[62, 113, 134, 119, 53]","[9042, 10106, 11423, 7958, 6528]","[9328, 7045, 9584, 6952, 6285]","[12, 13, 13, 11, 10]","[12, 10, 12, 10, 10]"
99,EUW1_6029767351,2114,CLASSIC,2,"[Yorick, Evelynn, Ziggs, Caitlyn, Rell]","[Darius, Udyr, Katarina, Kaisa, Soraka]","[83, 28, 115, 51, 526]","[122, 77, 55, 145, 16]","[17702, 15587, 18969, 15044, 11524]","[19011, 16492, 15569, 19376, 16728]","[17, 16, 18, 16, 14]","[18, 17, 16, 18, 17]"

In [16]:
data2 = data[["championId1"]].head()
data2

               championId1
0  [134, 96, 517, 555, 11]
1     [86, 20, 38, 99, 84]
2  [161, 120, 48, 91, 238]
3    [81, 20, 25, 45, 145]
4  [777, 22, 115, 222, 74]

In [18]:
print(type(data2.championId1[0]))

<class 'list'>

In [21]:
data_f= pd.DataFrame(data2.championId1.to_list(), columns=['1', '2','3','4','5'])
print(data_f)

     1    2    3    4    5
0  134   96  517  555   11
1   86   20   38   99   84
2  161  120   48   91  238
3   81   20   25   45  145
4  777   22  115  222   74